### ISSUE TITLE
Does primus-cluster work with primus-multiplex

### ISSUE THREAD

**Issue by afrozl** [neoziro/primus-cluster#18]
Does it currently, or can it work with [primus-multiplex](https://github.com/cayasso/primus-multiplex)  or [substream](https://github.com/primus/substream)?

**Comment by neoziro** [comment]
@afrozl multiplex probably, substream I don't know

**Comment by afrozl** [comment]
Just tried with multiplex. No luck, I'll try to reach the author of that plugin. I see that he was working to provide compatibility a year ago, but no updates since then.
